SHOPIFY_TIPS = [
    "Focus on social selling by adding 'Buy Now' links to your Facebook and Instagram posts.",
    "Customers are twice as likely to purchase a product with a 3D product image rather than a flat image",
    "On an average,65% of sales come from previous customers.",
    "Send visitors a reminder to recover their cart with an abandonment email. You may offer first order discount.",
    "Giveaways are a great idea to both engage existing customers and to raise awareness of your store.",
    "ROI of content marketing has been identified to be 8 times higher than that of traditional marketing.",
    "Several researches suggest that improvement in customer retention by 5% can increase profitability by up to 75%.",
    "Customer reviews, social presence and showcasing your dedication to security help create trust among the buyers.",
    "Adding Shopify collections to the navigation menu and throughout homepage helps customers to navigate to the desired product faster and increases the conversion rate by up to 30%.",
    "Optimize your store pages for the mobile experience as mobile traffic makes up 79% of the total traffic and 69% of orders of all traffic.",
    "With option to create wishlists you can get the buyers to subscribe for email updates and develop a relationship with them going forward.",
    "77% of buyers say a good customer loyalty program is more likely to make them stay with a brand.",
    "Loyalty and referral programs are powerful engines of word-of-mouth (WOM) marketing.",
    "Testimonials of happy customers to your store page can convince prospective buyers to trust your brand and increase the sales by well over 5%.",
    "Recognizing different audiences and sending them to landing pages with more specific messaging ensure conversions",
    "Did you know Shopify has great built-in settings to create SEO-friendly pages, giving you updatable meta fields (title, description, URL slug), automatically generating sitemaps, 301 redirects, and canonical URLs?",
    "Longer the load time of a website, higher the chances of visitors bouncing; for 1 to 5 sec the probability of bounce increases 90%.",
    " Matching the message on your landing page to the copy on your ad reduces friction, and gives your customer a better experience.",
    "While running sales or promotions, convey urgency by counting down till your promotion ends - 50% off flash sales - last 12 hours!!",
    "To have success with your ad campaigns use social proof in your ad copy.",
    "Choose third position rather than top ad spot as it still shows up at the top of the SERPs but costs less; helping you lower your CPC (cost per click).",
    "Long-tail keywords not only have benefit of lower competition and cost, but also are more likely to have higher post-click conversion rates",
    "A great way to upsell is by offering bundle deals or by referring customers to higher-cost products or services through a recommendation engine",
    "Popups, on an average, have a conversion rate of about 3.1% and the for highest performing ones it is up to of 9.28%.",
    "Blog posts are know to be ranked well on Google and can directly answer the questions the ideal customers are asking on that massive search engine.",
    "Nearly half of online shoppers expect a load time of two seconds or less for webpages and mobile users expect pages to load in four seconds or less.",
    "A delay of one second in load time of a website equates to an overall 7% loss in conversions.",
    "To model your pricing always consider what brands your clients may be comparing you to.",
    "Add an ""add to cart button"" on every page showing a product to improve your add-to-cart rate.",
    "Including several buttons that take a user directly to the checkout has nearly doubled the add to cart rate.",
    "Display your value-adds (like free shipping or returns, or a price guarantee,) in a site-wide header, or near the CTA, to convince on-the-fence shoppers to click add to cart when they otherwise might not.",
    "Preserving items in a shopping cart across devices, so a user has access to the same shopping cart when accessing it through a desktop or a mobile drives more sales.",
    "Interactions with customers who gave negative reviews are equally important. Offer them an apology and understand their grievances.",
    "It's important to set right expectations hence, provide shipping details clearly on the checkout page, and on the product description page.",
    "Engage your customers on social media handles by conducting webinars, shooting live videos, initiating sweep-takes etc.",
    "To know at what cost other stores are selling same product can be a good way to leverage cost as your unique selling point.",
    "For Conversion Rate Optimization follow 3-step rule i.e. site user should need only 3 clicks to reach the checkout page.",
    "Let ""Create an Account"" option be a part of the checkout process making it easier for a new user to make a purchase.",
    "Try to include newer and varied payment services as offering more options make it easier for prospects to give you their money.",
    "CTA buttons can be powerful tools if used to their maximum potential. Replacing ""Sign Up"" with ""Get started"" is a better action oriented and effective illustration.",
    "Incorporating scarcity in marketing strategy can increase click-through rate by 14% and double the sales.",
    "On an average offering upsells get of 70-95% of revenue and renewals.",
    "Add upsells by inserting pop-ups to offer better or more expensive item (or a related item) to your visitors when they add a related item to their cart.",
    "A survey suggests that 77% of customers won't make a purchase on a website if there?s no live chat option."
]

CURRENCY_SYMBOLS = {
    "EUR": "€",
    "ALL": "L",
    "BYN": "Br",
    "BAM": "KM",
    "BGN": "лв",
    "HRK": "kn",
    "CZK": "Kč",
    "DKK": "kr",
    "GEL": "ლარი",
    "HUF": "ft",
    "ISK": "Íkr",
    "CHF": "CHF",
    "MDL": "L",
    "MKD": "ден",
    "NOK": "kr",
    "PLN": "zł",
    "RON": "lei",
    "RUB": "₽",
    "RSD": "RSD",
    "SEK": "kr",
    "TRY": "₺",
    "UAH": "₴",
    "GBP": "£",
    "USD": "US$",
    "XCD": "$",
    "AWG": "ƒ",
    "ARS": "$",
    "BSD": "B$",
    "BBD": "$",
    "BMD": "$",
    "BZD": "BZ$",
    "BOB": "Bs",
    "BRL": "R$",
    "CAD": "C$",
    "KYD": "CI$",
    "CLP": "$",
    "COP": "$",
    "CRC": "₡",
    "CUP": "CUC$",
    "ANG": "ƒ",
    "DOP": "RD$",
    "FKP": "FK£",
    "GTQ": "Q",
    "GYD": "G$",
    "HTG": "G",
    "HNL": "L",
    "JMD": "J$",
    "MXN": "$",
    "NIO": "C$",
    "PAB": "B/.",
    "PYG": "₲",
    "PEN": "S/.",
    "SRD": "Sr$",
    "TTD": "TT$",
    "UYU": "$U",
    "VED": "Bs.",
    "AFN": "؋",
    "AMD": "դր",
    "AZN": "₼",
    "BHD": ".د.ب",
    "IQD": "ع.د",
    "IRR": "﷼",
    "ILS": "₪",
    "JOD": "ينار",
    "KWD": "ك",
    "LBP": "ل.ل",
    "SYP": "£S",
    "AED": "AED",
    "OMR": "ر.ع",
    "QAR": "ر.ق",
    "SAR": "SR",
    "YER": "﷼",
    "XAF": "FCFA",
    "XOF": "CFA",
    "DZD": "دج",
    "AOA": "Kz",
    "BWP": "P",
    "BIF": "FBu",
    "CVE": "CVE",
    "KMF": "CF",
    "CDF": "FC",
    "DJF": "Fdj",
    "EGP": "E£",
    "ERN": "Nkf",
    "ETB": "Br",
    "SZL": "L",
    "GMD": "D",
    "GHS": "GH₵",
    "GNF": "FG",
    "KES": "KSh",
    "LSL": "L",
    "LRD": "LD$",
    "LYD": "LD",
    "MGA": "Ar",
    "MWK": "K",
    "MUR": "₨",
    "MRU": "UM",
    "MAD": "DH",
    "MZN": "MT",
    "NAD": "N$",
    "NGN": "₦",
    "RWF": "R₣",
    "STN": "Db",
    "SCR": "SR",
    "SLL": "Le",
    "SOS": "Sh.So.",
    "ZAR": "R",
    "SSP": "SS£",
    "SDG": "SDG",
    "TZS": "TSh",
    "TND": "د.ت",
    "UGX": "USh",
    "AUD": "A$",
    "BDT": "৳",
    "BTN": "Nu",
    "BND": "B$",
    "KHR": "៛",
    "CNY": "¥ /元",
    "HKD": "$ / HK$ / “元”",
    "IDR": "Rp",
    "INR": "₹",
    "JPY": "¥",
    "KZT": "₸",
    "KGS": "som",
    "LAK": "₭",
    "MOP": "MOP$",
    "MYR": "RM",
    "MVR": "MRf",
    "MNT": "₮",
    "MMK": "K",
    "NPR": "Rs",
    "NZD": "$",
    "KPW": "₩",
    "PKR": "Rs",
    "PHP": "₱",
    "SGD": "S$",
    "KRW": "₩",
    "LKR": "Rs",
    "TWD": "NT$",
    "TJS": "TJS",
    "THB": "฿",
    "TMT": "m",
    "UZS": "som",
    "VND": "₫"
}